name: 'Documentation Checks'
description: 'Build and validate documentation to ensure it compiles correctly'

inputs:
  pnpm-version:
    description: 'pnpm version to use'
    required: false
    default: '10.4.1'
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        cache-dependency-path: docs/pnpm-lock.yaml

    - name: Install documentation dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
      working-directory: docs

    - name: Build documentation
      shell: bash
      run: pnpm build
      working-directory: docs