global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # StepFlow model servers
  - job_name: "text-models"
    static_configs:
      - targets: ["text-models:8080"]
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: "vision-models"
    static_configs:
      - targets: ["vision-models:8081"]
    metrics_path: /metrics
    scrape_interval: 10s

  # Model server health checks
  - job_name: "text-models-health"
    static_configs:
      - targets: ["text-models:8080"]
    metrics_path: /health
    scrape_interval: 5s

  - job_name: "vision-models-health"
    static_configs:
      - targets: ["vision-models:8081"]
    metrics_path: /health
    scrape_interval: 5s