apiVersion: apps/v1
kind: Deployment
metadata:
  name: stepflow-core
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: stepflow
        env:
        - name: RUST_LOG
          value: "debug"
        - name: RUST_BACKTRACE
          value: "1"
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stepflow-python-sdk
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: python-sdk
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stepflow-inference
spec:
  replicas: 0  # Disabled by default in dev
  template:
    spec:
      nodeSelector: {}  # Remove GPU requirement for dev
      tolerations: []   # Remove GPU tolerations
      containers:
      - name: inference
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
            nvidia.com/gpu: 0  # No GPU in dev
          limits:
            memory: "1Gi"
            cpu: "1000m"
            nvidia.com/gpu: 0