apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stepflow-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

patchesStrategicMerge:
  - deployment-patches.yaml

configMapGenerator:
  - name: stepflow-config
    behavior: replace
    files:
      - stepflow-config.yml

images:
  - name: localhost:5000/stepflow/core
    newTag: dev
  - name: localhost:5000/stepflow/python-sdk
    newTag: dev
  - name: localhost:5000/stepflow/inference
    newTag: dev