name: 'Python SDK Checks'
description: 'Run Python SDK tests and validate generated types using shared script logic'

inputs:
  python-version:
    description: 'Python version to test with'
    required: false
    default: '3.13'
  uv-version:
    description: 'uv version to install'
    required: false
    default: '0.7.5'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: true

    - name: Set up Python ${{ inputs.python-version }}
      shell: bash
      run: uv python install ${{ inputs.python-version }}
      working-directory: sdks/python

    - name: Install HTTP optional dependencies
      shell: bash
      run: uv sync --extra http
      working-directory: sdks/python

    # Run Python SDK checks using the shared script
    - name: Run Python SDK checks
      shell: bash
      run: ./scripts/check-python.sh