# Example StepFlow configuration with MCP plugin using mock server
# This shows how to configure an MCP server as a plugin for testing

plugins:
  # Built-in StepFlow components
  - name: builtin
    type: builtin

  # Mock MCP server for testing
  - name: mock-server
    type: mcp
    command: python3
    args: 
      - "/Users/zznate/Documents/GitHub/stepflow/stepflow-rs/crates/stepflow-components-mcp/tests/mock_mcp_server.py"

# Optional: Configure state storage
state_store:
  type: inMemory