[package]
name = "stepflow-components-mcp"
description = "Step execution plugins for executing MCP tools."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
# Core StepFlow dependencies
stepflow-core.workspace = true
stepflow-plugin.workspace = true
stepflow-protocol.workspace = true

# Async runtime and utilities
tokio.workspace = true
futures.workspace = true

# Serialization
serde.workspace = true
serde_json.workspace = true

# Error handling
error-stack.workspace = true
thiserror.workspace = true

# Utilities
indexmap.workspace = true
tracing.workspace = true