plugins:
  - name: builtin
    type: builtin
  - name: langflow
    type: stdio
    command: /Users/jordan.frazier/Documents/StepFlow/stepflow/.venv/bin/uv
    args: ["--project", "/Users/jordan.frazier/Documents/StepFlow/stepflow/sdks/langflow", "run", "python", "langflow_component_server_udf_only.py"]
    inherit_env: true