plugins:
  - name: builtin
    type: builtin
  - name: langflow
    type: stdio
    command: uv
    args: ["--project", "../../sdks/langflow", "run", "python", "langflow_component_server_udf_only.py"]