plugins:
  python:
    type: stepflow
    command: uv
    args: ["--project", "../../sdks/python", "run", "stepflow_sdk"]
  builtin:
    type: builtin
routing:
  - match: "/python/*"
    target: python
  - match: "*"
    target: builtin
