plugins:
  python:
    type: stepflow
    transport: stdio
    command: uv
    args: ["--project", "../../sdks/python", "run", "stepflow_py"]
  builtin:
    type: builtin
routes:
  "/python/{*component}":
    - plugin: python
  "/{*component}":
    - plugin: builtin
