plugins:
  - name: builtin
    type: builtin
  - name: custom
    type: stdio
    command: /Users/jordan.frazier/.cargo/bin/uv
    args: ["--project", "../../sdks/python", "run", "python", "custom_server.py"]