plugins:
  builtin:
    type: builtin
  custom:
    type: stepflow
    command: uv
    args: ["--project", "../../sdks/python", "run", "python", "custom_server.py"]
routing:
  - match: "/custom/*"
    target: custom
  - match: "*"
    target: builtin