plugins:
  - name: builtin
    type: builtin
  - name: custom
    type: stdio
    command: /Users/jordan.frazier/.cargo/bin/uv
    args: ["--project", "../../sdks/python", "run", "python", "custom_server.py"]
  - name: langflow-v1 # creates component server
    type: stdio
    command: /Users/jordan.frazier/.cargo/bin/uv
    args: ["--project", "../../sdks/python", "run", "langflow", "run"]