plugins:
  builtin:
    type: builtin
  custom:
    type: stepflow
    transport: stdio
    command: uv
    args: ["--project", "../../sdks/python", "run", "python", "custom_server.py"]
routes:
  "/custom/{*component}":
    - plugin: custom
  "/{*component}":
    - plugin: builtin