plugins:
  builtin:
    type: builtin
  python:
    type: stepflow
    transport: stdio
    command: uv
    args: ["--project", "../../sdks/python", "run", "stepflow_sdk"]
routes:
  "/builtin/{*component}":
    - plugin: builtin
  "/python/{*component}":
    - plugin: python
