name: Release - Dispatch

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  dispatch-release:
    name: Dispatch Release Build
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release:stepflow-rs')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Extract version from Cargo.toml
        id: version
        working-directory: stepflow-rs
        run: |
          VERSION=$(grep '^version = ' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=stepflow-rs-$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Dispatch release build
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"build-release","client_payload":{"version":"${{ steps.version.outputs.version }}","tag":"${{ steps.version.outputs.tag }}"}}'

      - name: Summary
        run: |
          echo "## Release Build Dispatched" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Dispatched release build for **stepflow-rs v${{ steps.version.outputs.version }}**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Tag:** ${{ steps.version.outputs.tag }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The release build workflow will:" >> $GITHUB_STEP_SUMMARY
          echo "1. Build binaries for all platforms" >> $GITHUB_STEP_SUMMARY
          echo "2. Build and push Docker images" >> $GITHUB_STEP_SUMMARY
          echo "3. Verify all artifacts" >> $GITHUB_STEP_SUMMARY
          echo "4. Create git tag and GitHub release" >> $GITHUB_STEP_SUMMARY